Repository Vishakha-singal/ReachAPI, pull requests merged in 2019-02, with the labels that each got.

#32 Issue #31 Added code to save registration token generated via FCM to …
  lib/json.jar
  src/edu/asu/heal/core/api/models/Patient.java
  src/edu/asu/heal/core/api/resources/PatientResource.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: Sprint 1, enhancement

#14 Task#1
  lib/apache-httpcomponents-httpclient.jar
  lib/apache-httpcomponents-httpcore.jar
  lib/commons-logging-1.1.2.jar
  src/edu/asu/heal/core/api/models/IHealModelType.java
  src/edu/asu/heal/core/api/models/NotificationData.java
  src/edu/asu/heal/core/api/models/NotificationRequestModel.java
  src/edu/asu/heal/core/api/resources/ActivityInstanceResource.java
  src/edu/asu/heal/core/api/service/HealService.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: Sprint 1, enhancement

#33 Task#12
  src/edu/asu/heal/core/api/models/NotificationData.java
  src/edu/asu/heal/core/api/models/NotificationRequestModel.java
  src/edu/asu/heal/core/api/resources/ActivityInstanceResource.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: Sprint 1, enhancement

#35 Added missing code for emotion to work.
  src/edu/asu/heal/reachv3/api/models/Emotions.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: Sprint 1, bug

#84 Issue #82 and Issue #83 - Scheduled both cron job accroding to timing…
  src/edu/asu/heal/core/api/resources/HourlyScheduledTask.java
  src/edu/asu/heal/core/api/resources/MidnightScheduledTask.java
  src/edu/asu/heal/core/api/resources/SchedulerMain.java
  src/edu/asu/heal/core/api/service/HealService.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: Sprint 2, bug
